language: csharp
solution: Quartz.RedisJobStore.Async.sln
mono: none
dotnet: 2.1.104

script:
 - dotnet restore
 - cd Quartz.RedisJobStore.Async.UnitTest
 - dotnet test
 - dotnet build -c Release
 - dotnet pack -c Release /p:PackageVersion=1.0.${TRAVIS_BUILD_NUMBER}
